# Configuration for golangci-lint v2+
# Based on https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"

run:
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 10
  max-same-issues: 3

linters:
  enable:
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - gosec
    - govet
    - lll
    - misspell
    - staticcheck
    - unparam
    - unused
    - nestif
    - prealloc
    - nolintlint
    - copyloopvar

  settings:
    funlen:
      lines: 150
      statements: 80
    nestif:
      min-complexity: 8
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '0'
        - '1'
        - '2'
        - '10'
        - '100'
        - '1000'
    lll:
      line-length: 160
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - unnamedResult
        - preferFprint
        - rangeValCopy
        - hugeParam
        - ifElseChain
        - paramTypeCombine
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/sirupsen/logrus"
              desc: "not allowed"
            - pkg: "github.com/pkg/errors"
              desc: "Should be replaced by standard lib errors package"
          allow:
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/charmbracelet/bubbletea
            - github.com/charmbracelet/lipgloss
            - t212-taxes/internal/app/cli
            - t212-taxes/internal/app/tui
            - t212-taxes/internal/domain/calculator
            - t212-taxes/internal/domain/parser
            - t212-taxes/internal/domain/types

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - mnd
          - funlen
          - gocyclo
          - goconst
          - dupl
          - errcheck
          - gosec
          - lll
      - path: cmd/
        linters:
          - mnd
          - lll
      - path: internal/app/tui/
        linters:
          - staticcheck
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - gosec
        text: "G304"  # File inclusion via variable - common in CLI tools
      - linters:
          - gosec
        text: "G204"  # Subprocess launched with variable - for browser opening
      - linters:
          - gosec
        text: "G601"  # Implicit memory aliasing - often false positive 