# Configuration for golangci-lint v2.1.6+
# See https://golangci-lint.run/product/migration-guide for details

version: 2

run:
  timeout: 10m
  go: "1.21"

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "not allowed"
          - pkg: "github.com/pkg/errors"
            desc: "Should be replaced by standard lib errors package"
        allow:
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/charmbracelet/bubbletea
          - github.com/charmbracelet/lipgloss
          - t212-taxes/internal/app/cli
          - t212-taxes/internal/app/tui
          - t212-taxes/internal/domain/calculator
          - t212-taxes/internal/domain/parser
          - t212-taxes/internal/domain/types
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/Lizzergas/go-t212-taxes
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - hugeParam # Disable for TUI models
      - rangeValCopy # Disable for struct iterations
      - unnamedResult # Allow unnamed results for simple functions
  funlen:
    lines: 120
    statements: 60
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Lizzergas/go-t212-taxes)
  nestif:
    min-complexity: 5
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  mnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign

linters:
  disable-all: true
  enable:
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - gosec
    - govet
    - lll
    - misspell
    - staticcheck
    - unparam
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
        - goconst
        - dupl
    - path: internal/app/tui/
      linters:
        - funlen # TUI methods can be longer due to formatting
        - gocyclo # TUI methods can be complex due to state management
    - path: internal/app/cli/
      linters:
        - funlen # CLI methods can be longer due to formatting
    - path: internal/domain/parser/
      linters:
        - gocyclo # Parser methods can be complex
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - text: "should not use dot imports"
      linters:
        - stylecheck
    - text: "Potential file inclusion via variable"
      linters:
        - gosec
    - text: "Subprocess launched with variable"
      linters:
        - gosec
    - text: "Implicit memory aliasing in for loop"
      linters:
        - gosec
    - text: "missing cases in switch of type types.TransactionType"
      linters:
        - exhaustive
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10 