# Configuration for golangci-lint v2.1.6
# Focused on essential linters since linters-settings not supported

version: "2"

run:
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 15
  max-same-issues: 5

linters:
  enable:
    - errcheck      # Essential: check for unhandled errors
    - govet         # Essential: official Go static analysis
    - staticcheck   # Essential: high-quality static analysis
    - unused        # Essential: find unused code
    - misspell      # Essential: catch typos
    - gocyclo       # Important: complexity checking (we fixed the major one)
    - unparam       # Important: unused parameters (we fixed main issues)
    - prealloc      # Important: performance (we fixed main issues)
    # Disabled problematic linters:
    # - funlen: too strict with default settings (60 lines)
    # - lll: too strict with default settings (120 chars vs our 160)
    # - gosec: too many false positives for CLI tools
    # - gocritic: too many style suggestions
    # - nestif: covered by gocyclo
    # - mnd: magic number detection too strict
    # - goconst: string constant detection too strict
    # - nolintlint: directive linter not essential 