# Configuration for golangci-lint v2+
# Based on https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322

version: "2"

run:
  timeout: 10m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - gosec
    - govet
    - lll
    - misspell
    - staticcheck
    - unparam
    - unused
    - nestif
    - prealloc
    - nolintlint
    - copyloopvar

  settings:
    funlen:
      lines: 120
      statements: 60
    nestif:
      min-complexity: 5
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - unnamedResult
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/sirupsen/logrus"
              desc: "not allowed"
            - pkg: "github.com/pkg/errors"
              desc: "Should be replaced by standard lib errors package"
          allow:
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/charmbracelet/bubbletea
            - github.com/charmbracelet/lipgloss
            - t212-taxes/internal/app/cli
            - t212-taxes/internal/app/tui
            - t212-taxes/internal/domain/calculator
            - t212-taxes/internal/domain/parser
            - t212-taxes/internal/domain/types

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - mnd
          - funlen
          - gocyclo
          - goconst
          - dupl
          - errcheck
          - gosec
      - path: cmd/
        linters:
          - mnd
      - linters:
          - lll
        source: "^//go:generate " 