# GoReleaser configuration
# This file is prepared for future use when you want to switch from GitHub Actions
# to GoReleaser for more advanced release management

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/t212-taxes
    id: t212-taxes
    binary: t212-taxes
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    # Ignore certain combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats: [tar.gz]
    # Use zip for Windows
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: Lizzergas
    name: go-t212-taxes
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## T212 Taxes {{ .Tag }}
    
    A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations.
    
  footer: |
    ## Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew tap Lizzergas/t212-taxes
    brew install t212-taxes
    ```
    
    ### Go Install
    ```bash
    go install github.com/Lizzergas/go-t212-taxes/cmd/t212-taxes@{{ .Tag }}
    ```
    
    ### Docker
    ```bash
    docker run --rm -v $(pwd)/exports:/app/data ghcr.io/lizzergas/go-t212-taxes:{{ .Tag }} analyze --dir /app/data
    ```
    
    **Full Changelog**: https://github.com/Lizzergas/go-t212-taxes/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/lizzergas/go-t212-taxes:{{ .Tag }}"
      - "ghcr.io/lizzergas/go-t212-taxes:v{{ .Major }}"
      - "ghcr.io/lizzergas/go-t212-taxes:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/lizzergas/go-t212-taxes:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/Lizzergas/go-t212-taxes"
    extra_files:
      - config.yaml

# Homebrew cask - using main repository (recommended over brews for pre-compiled binaries)
homebrew_casks:
  - name: t212-taxes
    repository:
      owner: Lizzergas
      name: go-t212-taxes  # Use main repository
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"  # Use standard GitHub token
    url_template: "https://github.com/Lizzergas/go-t212-taxes/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Homebrew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks  # Will create Casks/ directory in your repo
    homepage: "https://github.com/Lizzergas/go-t212-taxes"
    description: "A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations"
    skip_upload: auto
    # For unsigned binaries, we need to disable quarantine
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/t212-taxes"]
          end

# Snapcraft (Ubuntu Store) - DISABLED for now (requires snapcraft in CI)
# snapcrafts:
#   - name: t212-taxes
#     publish: false # Set to true when ready to publish to Snap Store
#     summary: Trading 212 CSV processor and tax calculator
#     description: |
#       A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations.
#       
#       Features:
#       - Process multiple CSV files with yearly validation
#       - Calculate financial metrics (deposits, gains, dividends)
#       - Generate yearly and overall investment reports
#       - Beautiful terminal UI with detailed breakdowns
#     grade: stable
#     confinement: strict
#     license: MIT
#     base: core20
#     apps:
#       t212-taxes:
#         command: t212-taxes
#         plugs: ["home", "network"]

# Scoop (Windows package manager) - DISABLED for now
# scoops:
#   - name: t212-taxes
#     repository:
#       owner: Lizzergas
#       name: go-t212-taxes  # Use main repository
#       branch: main
#       token: "{{ .Env.GITHUB_TOKEN }}"  # Use standard GitHub token
#     url_template: "https://github.com/Lizzergas/go-t212-taxes/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     commit_author:
#       name: goreleaserbot
#       email: bot@goreleaser.com
#     commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
#     directory: bucket  # Will create bucket/ directory in your repo
#     homepage: "https://github.com/Lizzergas/go-t212-taxes"
#     description: "A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations"
#     license: MIT
#     skip_upload: auto 