# This file was generated by GoReleaser. DO NOT EDIT.
cask "t212-taxes" do
  desc "A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations"
  homepage "https://github.com/Lizzergas/go-t212-taxes"
  version "1.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t212-taxes"

  on_macos do
    on_intel do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.21/go-t212-taxes-darwin-x86_64.tar.gz"
      sha256 "1a9069f204efdce208cd5abfb41545a8a7af01d70cbe4749eb4af429770e51e1"
    end
    on_arm do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.21/go-t212-taxes-darwin-arm64.tar.gz"
      sha256 "1caaf5eed6ae537afb0aadd25efde841765086a81a65fece58d7a8fa290fe9b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.21/go-t212-taxes-linux-x86_64.tar.gz"
      sha256 "1328e63fc7ea4db9f916dbb1946e890a485d62b4da48c351517227754a576abd"
    end
    on_arm do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.21/go-t212-taxes-linux-arm64.tar.gz"
      sha256 "88e988d59d3964be1da5b0aedd289455184ec63f60834ebd532d622907847b8b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/t212-taxes"]
    end
  end

  # No zap stanza required
end
