# This file was generated by GoReleaser. DO NOT EDIT.
cask "t212-taxes" do
  desc "A comprehensive tool for processing Trading 212 CSV exports and calculating tax obligations"
  homepage "https://github.com/Lizzergas/go-t212-taxes"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "t212-taxes"

  on_macos do
    on_intel do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.2/go-t212-taxes-darwin-x86_64.tar.gz"
      sha256 "639500988ba2c5d8aac72782d7d6754cd0cd399f0970c969447fa6e25855cdfd"
    end
    on_arm do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.2/go-t212-taxes-darwin-arm64.tar.gz"
      sha256 "6fd157e3f13529b5db830ddbf900df2ea6b9a774887b267e85321ad9114a1ddb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.2/go-t212-taxes-linux-x86_64.tar.gz"
      sha256 "5f1374a31bb843a68c5a928cccd33d97076288243242bcd0773aae259e2fd5f9"
    end
    on_arm do
      url "https://github.com/Lizzergas/go-t212-taxes/releases/download/v1.0.2/go-t212-taxes-linux-arm64.tar.gz"
      sha256 "2cf6895a70aa04773177a9073b1b6b41fa237c77468bc4e9746049b065d6bdc7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/t212-taxes"]
    end
  end

  # No zap stanza required
end
