name: GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

env:
  GO_VERSION: '1.21'

jobs:
  # Run comprehensive test suite before building
  test:
    name: Pre-Release Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install testing tools
      run: |
        # Install golangci-lint
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
        # Install gosec for security scanning
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Make test script executable
      run: chmod +x scripts/test-all.sh

    - name: Run comprehensive test suite
      run: |
        echo "Running comprehensive test suite for release..."
        ./scripts/test-all.sh --verbose
        
        echo "✅ All tests passed - proceeding with release"

    - name: Run quality gate check (strict for releases)
      run: |
        echo "Running strict quality gate check for release..."
        chmod +x scripts/lint-check.sh
        ./scripts/lint-check.sh
        
        echo "✅ Quality gate passed - ready for release"

  # GoReleaser handles everything: binaries, Docker, Homebrew, Scoop
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Update release with additional installation instructions
  update-release:
    name: Update Release Notes
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
    - name: Update release with installation instructions
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        append_body: true
        body: |
          
          ## 📦 Additional Installation Methods
          
          **Homebrew (macOS/Linux):**
          ```bash
          brew tap Lizzergas/go-t212-taxes
          brew install t212-taxes
          ```
          
          **Scoop (Windows):**
          ```bash
          scoop bucket add t212-taxes https://github.com/Lizzergas/go-t212-taxes
          scoop install t212-taxes
          ```
          
          **Verify Installation:**
          ```bash
          t212-taxes version
          ```
          
          ---
          
          **🐛 Found an issue?** [Report it here](https://github.com/${{ github.repository }}/issues)
          **💬 Questions?** [Start a discussion](https://github.com/${{ github.repository }}/discussions)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 